version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
  pre_build:
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - cd PersonalWebsite
      - ng build --configuration=production
  post_build:
    commands:
      - echo Build completed on
artifacts:
  files:
    - dist/**/*