version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo install process started
      - cd website-source
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build --configuration=production
      - ng build --configuration=production --output-path=../output-files
  post_build:
    commands:
      - echo Build completed on
artifacts:
  files:
    - '**/*'
  base-directory: 'output-files'
  delete-path: yes